[
    {
        "deviceTypeOneName": "终端主机",
        "businessSoftware": [],
        "internal": "1",
        "isHaveDB": "0",
        "outageTime": "0",
        "deviceScore": "5",
        "licenseExpiredTime": "0",
        "storageTime": "1627004714688",
        "vendorChn": "黑龙江太平洋科技有限公司",
        "physicalRegion": "2",
        "deviceTypeTwo": "WS",
        "inputTime": "1627004714688",
        "deviceName": "fcytestTelnet",
        "deviceTypeTwoName": "工作站",
        "isVirtualMachine": "0",
        "safeDefendSoftware": [],
        "safetyOfTime": "0",
        "commissioningTime": "0",
        "security": "5",
        "database": [],
        "usability": "5",
        "orgCode": "00001000370000500007",
        "isFreeAsset": "0",
        "manageState": "0",
        "sourceCity": "石家庄市",
        "businessSector": "3",
        "sourceFactory": "one",
        "os": [],
        "isDelete": "1",
        "integrality": "5",
        "updateTime": "0",
        "deviceTypeOne": "5",
        "maintenanceTime": "0",
        "createTime": "1601605358546",
        "sourceProvince": "河北省",
        "isStandby": "0",
        "isImportantAsset": "0",
        "deviceModel": "SU-GAP2",
        "insertDataBaseFunction": "1",
        "sourcePrefecture": "长安区",
        "ipList": [{
            "type": "业务",
            "ipAddr": "12.168.131.12",
            "firm": "",
            "macAddr": "11:11:11:aa:a1:e1"
        }],
        "otherSoftware": []
    }
]
